### ISSUE TITLE
Input to caffe model

### ISSUE THREAD

**Issue by sharminpathan** [chirag0734/minions-project3#3]
In what way can we provide the feature vector as an input to create caffe model?

**Comment by chirag0734** [comment]
I think we can use LMDB for our requirement. There are layers which interacts with data like DataLayer, ImageDataLayer, HDF5 Layer etc. Data Layer will be useful for us.

**Comment by sharminpathan** [comment]
Yeah, LMDB provides faster access. Implemented!
